### PR TITLE
feat: allow dropping referer from headers

### PR DESCRIPTION
**Pull request by Rongronggg9**
also put all configurations on top

### CODE REVIEW

**Comment by netnr** [comment]
Extracting the configuration to the top may be for the convenience of modifying the configuration? I think the logic is scattered after the configuration is extracted, or the way to extract the configuration needs to be improved, for example: 
`keys: config.blocklist`

**Comment by Rongronggg9** [comment]
> Extracting the configuration to the top may be for the convenience of modifying the configuration? I think the logic is scattered after the configuration is extracted, or the way to extract the configuration needs to be improved, for example: `keys: config.blocklist`

I see. 8d2a07addda8ba273be0f7d60c12051584e60edb should have solved this problem.

**Comment by netnr** [comment]
```
const config = {
    sematext_token: "",
    dropReferer: false,
    blocklist: [""],
};
```
Please keep the same naming style

**Comment by Rongronggg9** [comment]
> ```
> const config = {
>     sematext_token: "",
>     dropReferer: false,
>     blocklist: [""],
> };
> ```
> 
> Please keep the same naming style

Fixed in b0a3b39e88d4b0ac1feee9b51fe57517c1242185.

**Pull request merged**
